
export enum Role {
  USER = 'user',
  MODEL = 'model',
}

export interface Message {
  id: string;
  role: Role;
  text: string;
  image?: string; // Base64
  audio?: boolean; // Marker if it was an audio message
  timestamp: Date;
}

export enum LakiMood {
  NEUTRAL = 'neutral',
  HAPPY = 'happy',
  SHY = 'shy',
  THINKING = 'thinking',
  LISTENING = 'listening',
  COACH = 'coach', // For fitness
  STUDY = 'study', // Wearing glasses
  MENTOR = 'mentor', // New: For Games, maybe wearing a little hat or holding a pointer?
}

export enum LakiShape {
  CLOUD = 'cloud',
  RABBIT = 'rabbit',
  CAT = 'cat',
  DOG = 'dog',
  WHALE = 'whale',
  FLOWER = 'flower',
  BIRD = 'bird',
}

export enum AppMode {
  CHAT = 'chat',
  GYM = 'gym',
  STUDY = 'study',
  GAME = 'game', // New mode
}

export enum ThemeMode {
  MORNING = 'morning',
  NOON = 'noon',
  SUNSET = 'sunset',
  NIGHT = 'night',
  ANXIETY_RELIEF = 'anxiety_relief', // Deep Blue
  HIGH_ENERGY = 'high_energy', // Orange Red
}

export interface UserSettings {
  language: 'zh' | 'en' | 'ja';
  timezone: string;
}

export type ImageSize = '1K' | '2K' | '4K';

export interface ImageGenerationConfig {
  prompt: string;
  size: ImageSize;
}

export interface JournalEntry {
  id: string;
  date: string;
  content: string; // The summary generated by Gemini
  emoji: string; // A mood emoji for the entry
}

export interface UserProfile {
  height?: string; // cm
  weight?: string; // kg
  targetWeight?: string; // kg - NEW field
  fitnessGoal?: string; // e.g. "Lose weight", "Build muscle"
  schedule?: string; // Text representation of calendar
  studyTopic?: string; // e.g. "React Hooks", "Calculus"
  heartRate?: string; // bpm (simulated)
  sleepHours?: string; // hours (simulated)
}
